### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNHtmlToPdf.convert') in iOS

### ISSUE THREAD

**Issue by rpgpunzalan** [christopherdro/react-native-html-to-pdf#174]
Everything is working smoothly on android but on iOS, I am getting this error. I tried checking the value of RNHTMLtoPDF and it has no null value. It sees convert as a function and all. I also have checked the options. Please help thanks

**Comment by euZebe** [comment]
Same here, which I fixed by following the indications [here](https://github.com/christopherdro/react-native-html-to-pdf/issues/131) 
`cd ios && pod install`
then `react-native run-ios` to reinstall app.
Hope this helps.

**Comment by rpgpunzalan** [comment]
Unfortunately, it's still not working. I also tried deleting node modules, reinstalling them, deleting pods folder, and reinstalling those pods. Still no luck

**Comment by vitolipari** [comment]
I have the same error

**Comment by lucaspiressimao** [comment]
Not working for me too ...
